version: "3.9"
services:
  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    restart: always
    networks:
      - inner-net
  pg:
    image: postgres:14.8-alpine3.18
    container_name: pg
    env_file:
      - .env
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/001.sql
      - data:/var/lib/postgresql/data
    networks:
      - inner-net
    ports:
      - "5431:5432"

  wsgi:
    container_name: wsgi
    build:
      context: .
      dockerfile: api
    env_file:
      - .env
    depends_on:
      - pg
    networks:
      - inner-net
    volumes:
      - storage:/proj/storage/media

  asgi:
    container_name: asgi
    build:
      context: .
      dockerfile: ws
    env_file:
      - .env
    ports:
      - "3301:3001"
    depends_on:
      - pg
      - redis
      - wsgi
    networks:
      - inner-net
    volumes:
      - storage:/proj/storage/media
  proxy:
    build:
      context: .
      dockerfile: front
    container_name: proxy
    depends_on:
      - asgi
      - wsgi
    ports:
      - "80:80"
    volumes:
      - ./storage/media:/usr/share/nginx/html/media
      - storage:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inner-net

volumes:
  data:
  storage:

networks:
  inner-net:
    name: inner-net

