# Generated by Django 4.2.15 on 2024-08-31 12:29

import collector.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('YANDEX', 'YANDEX'), ('GOOGLE', 'GOOGLE'), ('MAIL', 'MAIL')], max_length=30)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_message', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(default=collector.models.generate_filename, max_length=36)),
            ],
            options={
                'unique_together': {('service', 'username', 'password')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=2048, null=True)),
                ('dispatch_date', models.DateTimeField()),
                ('receipt_date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=16384, null=True)),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector.mail')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='media/', location='./storage/media'), upload_to=collector.models.generate_filename)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='collector.message')),
            ],
        ),
    ]
