# Generated by Django 4.2.15 on 2024-08-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='last_message',
            field=models.IntegerField(null=True),
        ),
    ]
