# Generated by Django 4.2.15 on 2024-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_mail_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dispatch_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='receipt_date',
            field=models.CharField(max_length=255),
        ),
    ]
